### ISSUE TITLE
[rdf] Load an RDF file as unary and binary facts.

### ISSUE THREAD

**Issue by irina-dragoste** [knowsys/rulewerk#115]
Currently, each RDF triple is translated as a Java fact associated to a predicate of arity 3.
We wish to translate RDF triples role assertions into ternary facts, and class assertions into binary facts.

**Comment by mkroetzsch** [comment]
This has been implemented in Rulewerk 0.7.0. The constructor ```RdfModelConverter(boolean skolemize, String triplePredicateName)``` can be used with ```null``` for the predicate name to get this behaviour.
