### ISSUE TITLE
Core: rule files in eclipse

### ISSUE THREAD

**Issue by irina-dragoste** [knowsys/rulewerk#150]
- integrate rule files into eclipse (syntax highlighting, auto-completion, auto-suggest, refactoring,  auto-formatting, etc), all functionalities that are available for Java syntax

**Comment by irina-dragoste** [comment]
We can look into language servers

**Comment by alloka** [comment]
This is a plugin that can be used to construct a language, it seems reliable and a lot of people are using it, maybe if someone thinks it is relatable we can proceed.

https://www.eclipse.org/Xtext/index.html

**Comment by alloka** [comment]
http://www.liclipse.com/text/supported_languages.html 
this is also a plugin for eclipse3 that supports introducing a new language and it has syntax highlighting, it might be an option to consider as well.

**Comment by mmarx** [comment]
It seems to me that Xtext would be the way to go: it's an actively maintained part of the eclipse platform, designed specifically to build eclipse plugins for new languages, and it can also generate a language server.

**Comment by alloka** [comment]
https://github.com/mn-mikke/Model-driven-Pretty-Printer-for-Xtext-Framework/wiki/Standard-Way-of-Syntax-Highlighting-in-Xtext-Framework this might be useful as well, but I need to do further investigations to get better knowledge about xtext but we need to agree first on this.

**Comment by alloka** [comment]
https://wiki.eclipse.org/FAQ_How_do_I_provide_syntax_coloring_in_an_editor%3F this might be an easy way to do syntax highlighting within eclipse using the parser we currently have as far as I understand, need to confirm this as well.

**Comment by mmarx** [comment]
> https://wiki.eclipse.org/FAQ_How_do_I_provide_syntax_coloring_in_an_editor%3F this might be an easy way to do syntax highlighting within eclipse using the parser we currently have as far as I understand, need to confirm this as well.

It's not, it requires writing a platform plugin and implementing a custom editor (both of which are taken care of by xtext), and it also doesn't work with our current parser.

**Comment by alloka** [comment]
A note: Xtext doesn't provide syntax highlighting in case of integrating it with LSP.
cf: https://github.com/eclipse/xtext-core/issues/283

**Comment by alloka** [comment]
https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#highlighting This contains the features found in Xtext including refactoring, further elaborating tutorials are needed.

**Comment by mmarx** [comment]
> A note: Xtext doesn't provide syntax highlighting in case of integrating it with LSP.
To clarify: the language server doesn't do syntax highlighting. The generated eclipse plugin still does.

**Comment by alloka** [comment]
[Documentation.pdf](https://github.com/knowsys/vlog4j/files/4218799/Documentation.pdf)

Xtext Documentation

**Comment by mmarx** [comment]
I have removed the link. Please don't upload random documents you find on the Internet to the issue tracker, especially if it's unclear what license the content is under, if any. It doesn't help that that particular version of the documentation refers to an eight-year-old version of Xtext.

The current version of the Xtext documentation is found here: https://www.eclipse.org/Xtext/documentation/index.html

**Comment by alloka** [comment]
Is this way possible for us to get a standalone application? 

https://github.com/echebbi/standalone-xtext-example#4-use-xtext-in-a-standalone-application

**Comment by alloka** [comment]
I figured out a way which is to export the xtext project as a feature and it can be installed in any eclipse and it is working and tested, another way but not test is through maven.

**Comment by mmarx** [comment]
Tracking all further progress in https://github.com/knowsys/rulewerk-plugin/.
