### ISSUE TITLE
Unexpected Reasoning result

### ISSUE THREAD

**Issue by mrnolte** [knowsys/rulewerk#166]
Hey there,
I have a problem regarding the reasoning using version 0.5.0 per maven and Java 13. Consider the following code:
```java
final KnowledgeBase KB = RuleParser.parse( 
	  "B(?x2) :- A(?x2) .\n" // statement 1
	+ "B(star) .\n" // statement 2
	+ "Rel(r0) :- C2(cy), B(?x0) .\n" // statement 3
	+ "C2(cy) ."); // statement 4
		
try (final Reasoner reasoner = new VLogReasoner(KB)) {
	if (!reasoner.reason()) {
		throw new RuntimeException();
	}
	try (var result = reasoner.answerQuery(Expressions.makePositiveLiteral("Rel", Expressions.makeUniversalVariable("a")), false)) {
		while (result.hasNext()) {
			System.out.println(result.next());
		}
	}
}
```
This does not print anything, although I would expect `Rel(r0)` because of the statements 2 - 4. Interestingly, without statement 1 `Rel(r0)` does get printed. Do I miss something about the reasoning or is this behaviour a bug?

Cheers,
Robin Nolte

**Comment by mmarx** [comment]
This seems to be a bug in VLog, c.f. karmaresearch/vlog#43.

**Comment by mmarx** [comment]
Fixed in current upstream VLog.
