### ISSUE TITLE
Core: get chase result as a stream/iterator/collection of Facts/PositiveLiterals

### ISSUE THREAD

**Issue by irina-dragoste** [knowsys/rulewerk#167]
`Reasoner `should expose a `getInferences` method that returns a stream/iterator/collection of Java objects representing all (explicit and implicit) facts in the result of the chase, as well as the correctness (see `Reasoner#writeInferences`).

-[ ] have a general `forEachInference(BiConsumer<Predicate, List<Term>>)`, in the style of `Iterator#forEachRemaining`, to keep the common parts of the implementation of `writeInferences `and `getInferences `in a single place

-[ ] move `writeInferences `and `getInferences `to `Reasoner `interface as default methods, since they would no longer be specific to VLog

-[ ] round-tripping for `writeInferences` can now be tested, as the Parser accepts facts with nulls.

**Comment by mmarx** [comment]
This has landed on master.
