### ISSUE TITLE
Missing inference due to other rules in a KB

### ISSUE THREAD

**Issue by mrnolte** [knowsys/rulewerk#175]
Hey there,
Unfortunately I currently do not have the time to find a minimal example, but consider the knowledge base written down in [this file](https://github.com/knowsys/rulewerk/files/4684913/error.txt).
The KB contains the following rules (among many other):
```
VANDALISMRESERVEDENTITIESSUPPREL0(VANDALISMRESERVEDENTITIESSUPPRULE50) :- VANDALISMRESERVEDENTITIESSUPPPREDICATEVANDALISMRESERVEDENTITIESFORTOPBOTTOMSAMEbottom00(VANDALISMRESERVEDENTITIESFORTOPBOTTOMSAMEbottomconstant0), VANDALISMRESERVEDENTITIESDATALOGhttppurobolibrarorgoboBFO00000040(?VANDALISMRESERVEDENTITIESUNIVERSALVARS70), VANDALISMRESERVEDENTITIESDATALOGhttppurobolibrarorgoboBFO00000200(?VANDALISMRESERVEDENTITIESUNIVERSALVARS70) .
VANDALISMRESERVEDENTITIESSUPPPREDICATEVANDALISMRESERVEDENTITIESFORTOPBOTTOMSAMEbottom00(VANDALISMRESERVEDENTITIESFORTOPBOTTOMSAMEbottomconstant0) .
VANDALISMRESERVEDENTITIESDATALOGhttppurobolibrarorgoboBFO00000040(VANDALISMRESERVEDENTITIESCRITICALCONSTANT0) .
VANDALISMRESERVEDENTITIESDATALOGhttppurobolibrarorgoboBFO00000200(VANDALISMRESERVEDENTITIESCRITICALCONSTANT0) .
```
These rules obviously entail the fact `VANDALISMRESERVEDENTITIESSUPPREL0(VANDALISMRESERVEDENTITIESSUPPRULE50)` and, when reasoned over on their own, do so using the current snapshot build. However, the knowlegde base contained in the above file does not and the following test fails:
```java
@Test
public void testReasoner() throws ParsingException, IOException {
	final KnowledgeBase kb = RuleParser.parse(new FileInputStream(Paths.get("error.txt").toFile()));
	try (final Reasoner reasoner = new VLogReasoner(kb)) {
		reasoner.reason();
		try (var result = reasoner.answerQuery(Expressions.makePositiveLiteral("VANDALISMRESERVEDENTITIESSUPPREL0",
				Expressions.makeAbstractConstant("VANDALISMRESERVEDENTITIESSUPPRULE50")), false)) {
			assertTrue(result.hasNext());
		}
	}
}
```

Btw, thank you guys a lot for your excellent work, fast reactions and support! It is great to have both Vlog and Rulewerk as an open source alternative to RDFox.

Cheers,
Robin

**Comment by mmarx** [comment]
This looks like another bug in VLog, but I'll have to take a closer look.

**Comment by CerielJacobs** [comment]
I tried converting the error.txt file to VLog input. I probably made errors there, but with VLog, I cannot reproduce this problem, that is, the materialization contains the required fact.

**Comment by CerielJacobs** [comment]
I indeed made some errors in converting. Please ignore my earlier comment.

**Comment by CerielJacobs** [comment]
Confirming that it is a VLog bug.

**Comment by mmarx** [comment]
Thanks for reproducing this, @CerielJacobs!

**Comment by CerielJacobs** [comment]
Hi,
this issue should be fixed. Fix is in the master branch of VLog.

**Comment by mrnolte** [comment]
Thank you very much, I cannot reproduce the bug anymore!
