### ISSUE TITLE
Standalone client on M1 Mac produce this error: (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

### ISSUE THREAD

**Issue by a-alhazmi** [knowsys/rulewerk#220]
Hello, 
I am PhD student, who working on ForBackBench project. I am using Rulewerk as a standalone client in my project. The client jar file working perfectly on Linux and Mac with Intel processors. 

At some point, I tried to run the client on the new M1 Mac (Mac with architecture arm64) , but I got that error:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: while loading kognac-core: /private/var/folders/nk/mg7msvvx4rg7d9bht0l7lnwr0000gp/T/VLog-tmp6815360794293855698/libkognac-core.dylib: dlopen(/private/var/folders/nk/mg7msvvx4rg7d9bht0l7lnwr0000gp/T/VLog-tmp6815360794293855698/libkognac-core.dylib, 0x0001): tried: '/private/var/folders/nk/mg7msvvx4rg7d9bht0l7lnwr0000gp/T/VLog-tmp6815360794293855698/libkognac-core.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libkognac-core.dylib' (no such file)`
I downloaded the code again and tried to using the `build-vlog-library.sh` to build new client on the M1 Mac, but the error is still exist. 

How could I run the standalone client on M1 Mac?

**Comment by irina-dragoste** [comment]
Hello. This is a [VLog|https://github.com/karmaresearch/vlog] bug.
Did you try updating the VLog dependency version in the rulewerk-vlog pom file prior to running `build-vlog-library.sh` ? Perhaps if not, maven could use the old dependency and not the newly built one. 

In case you did, did you get this error when trying to build vLog, or did it build sucesfully?

**Comment by a-alhazmi** [comment]
Hello, Thanks for your answer. 

The Vlog dependency version in the` rulewerk-vlog` `pom.xml` file is: `<karmaresearch.vlog.version>1.3.5</karmaresearch.vlog.version>` , which match the Vlog release that in Vlog GitHub. 

It built successfully without any errors,  but when I run the client jar file it throws that error (incompatible architecture).

**Comment by irina-dragoste** [comment]
We see that the released karmaresearch.vlog (vlog-java) jar version 1.3.5 does not work on M1 Mac, as you reported in this bug. 

We want to see if the current main branch in VLog that is built on M1 Mac can run there successfully. When running `build-vlog-library.sh`, this builds a new VLog (specifically, `vlog-java.jar`) and places it in your local maven repository, with the version given by `<karmaresearch.vlog.version>` property.  To make sure the newly built `vlog-java.jar` is used, it is recommended to follow the steps below:

* Increase the version of `vlog-java` (in `rulewerk-vlog/pom.xml`) before executing the next steps.
* Delete (if existing) previous local builds (`local_builds` directory).
* Run [build-vlog-library.sh](https://github.com/knowsys/rulewerk/blob/master/build-vlog-library.sh) or execute the commands in this file manually. This will compile a local jar file on your system, copy it to ```rulewerk-vlog/lib/jvlog-local.jar```, and install the new jar in your local Maven repository in place of the distributed version of `vlog-java`.
* Run ```mvn install``` to test if the setup works.

Does the bug still occur when following these steps?

**Comment by irina-dragoste** [comment]
Also, what command issues this error? We want to make sure we can reproduce the bug.

**Comment by a-alhazmi** [comment]
Yes, I followed all these steps, and the error was there. The error was thrown not from build commands, it was from running the produced stand-alone jar file. 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: while loading kognac-core: /private/var/folders/nk/mg7msvvx4rg7d9bht0l7lnwr0000gp/T/VLog-tmp164877341971675468/libkognac-core.dylib: dlopen(/private/var/folders/nk/mg7msvvx4rg7d9bht0l7lnwr0000gp/T/VLog-tmp164877341971675468/libkognac-core.dylib, 0x0001): tried: '/private/var/folders/nk/mg7msvvx4rg7d9bht0l7lnwr0000gp/T/VLog-tmp164877341971675468/libkognac-core.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libkognac-core.dylib' (no such file)
	at karmaresearch.vlog.VLog.loadLibrary(VLog.java:72)
	at karmaresearch.vlog.VLog.<clinit>(VLog.java:22)
	at org.semanticweb.rulewerk.reasoner.vlog.VLogReasoner.<init>(VLogReasoner.java:82)
	at org.semanticweb.rulewerk.client.picocli.RulewerkClientMaterialize.run(RulewerkClientMaterialize.java:102)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at org.semanticweb.rulewerk.client.picocli.Main.main(Main.java:77)
```

The good news the problem is resolved. Here what I did:
- I run the Mac terminal with the option (Open using Rosetta ,  to use the architecture` i386` instead of` arm64`). 
- I changed the Java version to the latest version `Java 18.0.2` , (I was using `Java 11`).
- I deleted the `cmake` command, and installed it again.
- I deleted everything related to Rulewerk, then cloned the Rulewerk again.
- I run build-vlog-library.sh and follow the steps that you mentioned. 

And it worked.

**Comment by CerielJacobs** [comment]
This issue can probably be fixed by providing "universal" binaries for the Mac (these work for i386 as well as arm64). I'm looking into how to do this.

**Comment by irina-dragoste** [comment]
@a-alhazmi, Could you please try again on  M1 Mac with the provided VLog jar attached in [try-solve-vlog-bug-96.zip](https://github.com/knowsys/rulewerk/files/9438709/try-solve-vlog-bug-96.zip)? This `.zip` archive contains a jar with "universal binaries" for Mac, but we didn't have access to an M1 Mac to test it ourselves.

1.  extract `jvlog-local.jar` file from .zip, and save it in `rulewerk-vlog\lib` folder
2.  increase `<karmaresearch.vlog.version>1.3.5</karmaresearch.vlog.version>` version in `rulewerk-vlog\pom.xml` file
3.  run `mvn initialize -Pdevelopment` from `rulewerk-parent` dir
4.  run `mvn clean install`
5.  run what reasoning task was causing this bug before.

**Comment by irina-dragoste** [comment]
fixed here: https://github.com/karmaresearch/vlog/issues/96
